# Copyright 2022 Ketan Goyal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "periodic_task",
    srcs = [
        "periodic_task.py",
    ],
    imports = [
        ".",
    ],
    deps = [],
)

py_binary(
    name = "run",
    srcs = [
        "run.py",
    ],
    main = "run.py",
    deps = [
        ":periodic_task",
        "//python:inspector",
        "//tools/reader:reader_py",
    ],
)
