cc_binary(
    name = "run",
    srcs = [
        "run.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp:inspector",
        "//tools/common/storage",
        "@glog",
    ],
)